<!-- Develop a XML File to get details of employee name, salary and designation using internal and external DTD. -->

<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE employee SYSTEM "employee.dtd">
<employee>
    <name>John</name>
    <salary>10000</salary>
    <designation>Manager</designation>
</employee>

//employee.dtd
<!ELEMENT employee (name, salary, designation)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT salary (#PCDATA)>
<!ELEMENT designation (#PCDATA)>

//internal DTD
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE employee [
<!ELEMENT employee (name, salary, designation)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT salary (#PCDATA)>
<!ELEMENT designation (#PCDATA)>
]>
<employee>
    <name>John</name>
    <salary>10000</salary>
    <designation>Manager</designation>
</employee>